// Generated by CoffeeScript 1.7.1
(function() {
  test("addition of two values", function(assert) {
    console.log(running);
    return equal(3, add(1, 2), "Value expected to be three");
  });

}).call(this);

//# sourceMappingURL=add-test.map
